parameters:
#    dbu_core.example.class: Dbu\Bundle\CoreBundle\Example

services:
#    dbu_core.example:
#        class: %dbu_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
